### ISSUE TITLE
Dangerous semver range (>) in engines.node

### ISSUE THREAD

**Issue by duncwinn** [jthomas/cfbot#1] opened 2016-01-06 23:49 UTC
git clone and the cf push resulted in...

Downloaded buildpacks
Staging...
-------> Buildpack version 1.5.2
-----> Creating runtime environment

```
   NPM_CONFIG_LOGLEVEL=error
   NPM_CONFIG_PRODUCTION=true
   NODE_ENV=production
   NODE_MODULES_CACHE=true
```

-----> Installing binaries
       engines.node (package.json):  >=4.0.0
       engines.npm (package.json):   unspecified (use default)

```
   Resolving node version >=4.0.0 via semver.io...
   Downloading and installing node undefined...
   Downloaded []
   Unable to download node undefined; does it exist?
```

-----> Build failed

```
   We're sorry this build is failing! You can troubleshoot common issues here:
   https://devcenter.heroku.com/articles/troubleshooting-node-deploys

   Some possible problems:

   - Dangerous semver range (>) in engines.node
   http://docs.cloudfoundry.org/buildpacks/node/node-tips.html

   Love,
   Heroku
```

Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed

Any thoughts?

**Comment by jthomas** [comment] 2016-01-08 14:47
Hey Duncan. 

What CF platform are you running on? I'll try to run the app there and replicate.
Can you try deleting the app and re-pushing? I wonder if this was a transient issue with semver.io.

**Comment by jthomas** [comment] 2016-01-21 12:37
Is this still happening? Otherwise, I'll close this ticket.

**Closed as completed** 2016-01-31 17:56 UTC

**Comment by gavmac** [comment] 2017-02-12 22:19
Im having the exact same issue....any help would be awesome

**Comment by istafrica-dennw** [comment] 2018-07-18 14:11
the answer to the issue is to downgrade/upgrade your npm/yarn to match the remote on. It worked for me.

**Comment by mimi-tech** [comment] 2023-01-06 10:10
Heroku needs to know what version of Node.js to download for any app that is deployed on their platform. The convention is to specify a version requirement in the engines field of package.json.

```json
{
  "name": "myapp",
  "description": "a really cool app",
  "version": "1.0.0",
  "engines": {
    "node": "18.12.1",
    "npm": "8.19.2",
  }
}
```

Use this command to get the version of node you are using 
$ node --version

Use this command to get the version of npm you are using 
$ npm --version

Use this command to get the version of yarn you are using 
$ yarn --version

**Comment by trxsh1DEV** [comment] 2023-03-13 17:14
> A Heroku precisa saber qual versão do Node.js baixar para qualquer aplicativo implantado em sua plataforma. A convenção é especificar um requisito de versão no campo de mecanismos de package.json.
> 
> ```json
> {
>   "name": "myapp",
>   "description": "a really cool app",
>   "version": "1.0.0",
>   "engines": {
>     "node": "18.12.1",
>     "npm": "8.19.2",
>   }
> }
> ```
> 
> Use este comando para obter a versão do nó que você está usando $ node --version
> 
> Use este comando para obter a versão do npm que você está usando $ npm --version
> 
> Use este comando para obter a versão do fio que você está usando $ yarn --version

Thanks, this tip saved me
